# Generated by Django 5.1.3 on 2025-02-21 00:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='uuid')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('name', models.CharField(max_length=256, verbose_name='name')),
                ('code', models.CharField(max_length=256, verbose_name='code')),
                ('parents', models.ManyToManyField(blank=True, related_name='children', to='account.role', verbose_name='parent roles')),
                ('type', models.ForeignKey(limit_choices_to={'type': 'role_type'}, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='core.datalookup')),
            ],
            options={
                'verbose_name': 'role',
                'verbose_name_plural': 'roles',
                'db_table': 'roles',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='uuid')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('full_name', models.CharField(max_length=256, verbose_name='full name')),
                ('email', models.EmailField(max_length=256, unique=True, verbose_name='email')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='phone number')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('is_admin', models.BooleanField(default=False, verbose_name='staff')),
                ('password_reset_code', models.CharField(blank=True, max_length=6, null=True, verbose_name='password reset code')),
                ('password_reset_code_expiry', models.DateTimeField(blank=True, max_length=10, null=True, verbose_name='password reset code')),
                ('role', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='account.role')),
                ('state', models.ForeignKey(blank=True, limit_choices_to={'type': 'account_state'}, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='core.datalookup')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'db_table': 'users',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['created_at'], name='roles_created_at_idx'),
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['updated_at'], name='roles_updated_at_idx'),
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['deleted_at'], name='roles_deleted_at_idx'),
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('code',), name='roles_code_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['created_at'], name='users_created_at_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['updated_at'], name='users_updated_at_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['deleted_at'], name='users_deleted_at_idx'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('email__isnull', False), ('deleted_at__isnull', True)), fields=('email',), name='users_email_idx'),
        ),
    ]
